import { Play } from "./Alies";

export const initialState:Play = {
    drive_id        :0,
    hometeam       :"",
    awayteam       :"",
    hometeam_points :0,
    awayteam_points :0,
    ball_possession :"",
    ball_place      :"",
    ball_place_result:"",
    ball_on         :0,
    ball_on_result:0,
    down            :0,
    distance        :0,
    o_or_k          :"",
    play_type       :"",
    passer          :"",
    reciever        :"",
    pass_iscomplete :"",
    turnover_place  :true,
    turnover_yards  :0,
    carrier         :"",
    result          :"", 
    to_return_yards :0,
    tackler         :"",
    yards_gained    :0,
    kicker          :"",
    kick_distance  :0,
    punter          :"",
    punt_distance   :0,
    returner        :"",
    kick_isgood     :"",
    kick_result     :"",
    return_yards    :0,
    yards_recovered :0
}